-- Generated by tools/build_plugins.py - do not edit by hand.
return {
    count = 15,
    bytes = 620144,
    files = {
        { path = "commands.lua", hash = "d3946736", size = 45286 },
        { path = "comms.lua", hash = "48ae905b", size = 14759 },
        { path = "draw.lua", hash = "6dce69c9", size = 16777 },
        { path = "follow.lua", hash = "ca399511", size = 45041 },
        { path = "future.lua", hash = "fcf54833", size = 12344 },
        { path = "header.lua", hash = "b48114d7", size = 10055 },
        { path = "ialog.lua", hash = "68c4d1ba", size = 11863 },
        { path = "leader.lua", hash = "d86abae2", size = 24440 },
        { path = "main.lua", hash = "434fa30d", size = 33500 },
        { path = "menu.lua", hash = "a9a581fc", size = 55821 },
        { path = "rotation.lua", hash = "b137ae9c", size = 37698 },
        { path = "spells.lua", hash = "a6f11b3e", size = 52862 },
        { path = "store.lua", hash = "a17d9e8d", size = 15821 },
        { path = "ui.lua", hash = "06c99592", size = 181963 },
        { path = "window.lua", hash = "1c036452", size = 61914 },
    },
}
