-- Generated by tools/build_plugins.py - do not edit by hand.
return {
    count = 8,
    bytes = 187304,
    files = {
        { path = "commands.lua", hash = "9c8f195c", size = 33208 },
        { path = "draw.lua", hash = "7fc05b63", size = 14561 },
        { path = "follow.lua", hash = "fe5d8f00", size = 25838 },
        { path = "header.lua", hash = "8e5b1b27", size = 10113 },
        { path = "main.lua", hash = "2b01fc5b", size = 16263 },
        { path = "menu.lua", hash = "0f6e31bc", size = 22087 },
        { path = "rotation.lua", hash = "018597ad", size = 16357 },
        { path = "spells.lua", hash = "d8af1ef7", size = 48877 },
    },
}
