-- Generated by tools/build_plugins.py - do not edit by hand.
return {
    count = 11,
    bytes = 294760,
    files = {
        { path = "commands.lua", hash = "4be93871", size = 42765 },
        { path = "comms.lua", hash = "10bcc627", size = 13919 },
        { path = "draw.lua", hash = "c4197e8c", size = 16835 },
        { path = "follow.lua", hash = "f56d8d43", size = 29334 },
        { path = "header.lua", hash = "ac94121b", size = 10084 },
        { path = "leader.lua", hash = "17d5fd88", size = 23984 },
        { path = "main.lua", hash = "376c3212", size = 25178 },
        { path = "menu.lua", hash = "b9e683c2", size = 43783 },
        { path = "rotation.lua", hash = "804ec061", size = 20572 },
        { path = "spells.lua", hash = "744344fd", size = 52668 },
        { path = "store.lua", hash = "e47b3aaf", size = 15638 },
    },
}
